# Copyright 2020 Jim Schubert
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Auto Labeler
author: Jim Schubert
description: Automatically label issues and pull requests via configuration
inputs:
  GITHUB_TOKEN:
    description: 'Github token for the repository'
    required: true
  config_path:
    description: 'Configuration path to labeler config, relative to repository root'
    required: false
    default: '.github/labeler.yml'
branding:
  icon: 'tag'
  color: 'orange'
runs:
  using: docker
  image: docker://jimschubert/labeler-action:latest
  # image: Dockerfile
